type = "card"
title = "Awards"
description = "Selected honors, scholarships, and awards."

[[items]]
title = "McGill Engineering Doctoral Award (MEDA)"
subtitle = "McGill University"
date = "2024"
content = ""

[[items]]
title = "Ciro Robert Martoni Fellowship in Sustainable Engineering"
subtitle = "McGill University"
date = "2024"
content = ""

[[items]]
title = "Outstanding Postgraduate Student"
subtitle = "Hunan University"
date = "2022"
content = ""


[[items]]
title = "Outstanding Graduate"
subtitle = "Chang'an University"
date = "2020"
content = ""


[[items]]
title = "National Scholarship"
subtitle = "Ministry of Education of China"
date = "2017"
content = ""
