[site]
title = "Lei Liao"
description = "PhD student in Civil Engineering at McGill University."
favicon = "/favicon.svg"
last_updated = "August 10, 2026"

[author]
name = "Lei Liao"
title = "PhD Student"
institution = "McGill University"
avatar = "/Selfie.jpg"

[social]
# Contact information (leave blank or delete to hide)

email = "lei.liao@mail.mcgill.ca"
location = "Montreal,Quebec, Canada"
location_url = "https://sites.google.com/view/hmirlab/home"
location_details = [
  "MD165, macdonald Engineering Building,",
  "845 Rue Sherbrooke O, Montreal"
]
google_scholar = "https://scholar.google.com/citations?user=7JyFbrYAAAAJ&hl=en"
orcid = "https://orcid.org/my-orcid?orcid=0009-0005-9031-6870"
github = "https://github.com/RayLeoi"
linkedin = "https://www.linkedin.com/in/lei-liao-4825a72b6/"

[features]
# Show a like button on the about page
enable_likes = true

# Display all subpages on a single page
enable_one_page_mode = false

[i18n]
enabled = true
locales = ["en"]
default_locale = "en"
# "auto" means the locale will be determined by the browser's language setting, "fixed" means the locale will be fixed to the default locale (but can be switched still, if you want to disable, set "enable=false")
mode = "auto"
fixed_locale = "en"
# If true, PRISM will remember user's language preference in browser's localStorage
persist = false
# Show a language switcher on the top right corner
switcher = false

[i18n.labels]
zh = "中文"
en = "English"

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "Teaching"
type = "page"
target = "teaching"
href = "/teaching"

[[navigation]]
title = "Awards"
type = "page"
target = "awards"
href = "/awards"

[[navigation]]
title = "Services"
type = "page"
target = "services"
href = "/services"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"


[[navigation]]
title = "News"
type = "page"
target = "news-page"
href = "/news-page"
