[[news]]
date = "2026-07"
content = "Gave an oral presentation on our diffusion-based aftershock ground-motion generation research at the 13th National Conference on Earthquake Engineering (13NCEE) in Portland, Oregon."
%[[news]]
%date = "2025-09"
%content = "Starting my PhD at the University of Example"
%[[news]]
%date = "2025-11"
%content = "Our work has been accepted by a prestigious journal 🎉"
