type = "card"
title = "Services"
description = "Academic peer-review service."

[[items]]
title = "Journal Reviewer"
subtitle = "ASCE-ASME Journal of Risk and Uncertainty in Engineering Systems, Part A: Civil Engineering"
content = ""

[[items]]
title = "Conference Reviewer"
subtitle = "13th National Conference on Earthquake Engineering (13NCEE)"
content = ""
