type = "card"
title = "Teaching"
description = "Courses I have assisted with as a teaching assistant."

[[items]]
title = "CIVE 317 Structural Engineering"
subtitle = "Graduate Teaching Assistant"
date = "Fall 2024"
content = "Instructor: Prof. Yazhou (Tim) Xie."
tags = ["Undergraduate", "Structural Engineering"]

[[items]]
title = "CIVE 460 Matrix Structural Analysis"
subtitle = "Graduate Teaching Assistant"
date = "Winter 2025"
content = "Instructor: Prof. Yazhou (Tim) Xie."
tags = ["Undergraduate", "Structural Analysis"]

[[items]]
title = "CIVE 317 Structural Engineering"
subtitle = "Graduate Teaching Assistant"
date = "Fall 2025"
content = "Instructor: Prof. Yazhou (Tim) Xie."
tags = ["Undergraduate", "Structural Engineering"]
