type = "card"
title = "奖项"
description = "部分荣誉、奖学金与奖项。"

[[items]]
title = "麦吉尔工程博士奖（MEDA）"
subtitle = "麦吉尔大学"
date = "2024"
content = ""

[[items]]
title = "Ciro Robert Martoni 可持续工程奖学金"
subtitle = "麦吉尔大学"
date = "2024"
content = ""

[[items]]
title = "优秀研究生"
subtitle = "湖南大学"
date = "2022"
content = ""

[[items]]
title = "优秀毕业生"
subtitle = "长安大学"
date = "2020"
content = ""

[[items]]
title = "国家奖学金"
subtitle = ""
date = "2017"
content = ""
